### PR TITLE
Fix deprecation warning message  DHH-679

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by escowles** [comment]
I'm getting the same 10 deprecation warnings with this or without:

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (3 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/dams_objects_controller_spec.rb:56)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (4 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/dams_provenance_collection_parts_controller_spec.rb:18)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (4 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/dams_provenance_collections_controller_spec.rb:18)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (4 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/dams_source_captures_controller_spec.rb:18)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (3 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/dams_units_controller_spec.rb:16)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (4 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/mads_schemes_controller_spec.rb:15)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (5 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/pages_controller_spec.rb:69)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (5 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/pages_controller_spec.rb:74)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (5 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/pages_controller_spec.rb:116)

DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (4 levels) in <top (required)> at /Users/escowles/src/git/damspas/spec/controllers/pages_controller_spec.rb:150)

**Comment by VivianChu** [comment]
This PR fixes this deprecation warning
DEPRECATION WARNING: Calling URL helpers with string keys controller is deprecated. Use symbols instead. (called from block in _app_views_catalog__did_you_mean_html_erb__4084544216195817134_2187956840 at /Users/Vivian_Chu/git/tmp/damsrepo-oct24-14/damsrepo-tomcat/damspas/app/views/catalog/_did_you_mean.html.erb:5)

rspec ./spec/features/dams_unit_spec.rb:45

**Comment by VivianChu** [comment]
I created a jira ticket for the deprecation warning that you mentioned.

https://lib-jira.ucsd.edu:8443/browse/DHH-687

**Comment by escowles** [comment]
I'm not seeing any of the "Calling URL helpers with string keys controller is deprecated" warnings when I run rspec on the develop branch now.

**Comment by VivianChu** [comment]
That's strange.  Could you run this "rspec ./spec/features/dams_unit_spec.rb:45" on your local develop branch? Thanks

Vivian-Chus-MacBook-Pro:damspas Vivian_Chu$ rspec ./spec/features/dams_unit_spec.rb:45
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: include {:locations=>{"./spec/features/dams_unit_spec.rb"=>[45]}}
DEPRECATION WARNING: Calling URL helpers with string keys controller is deprecated. Use symbols instead. (called from block in _app_views_catalog__did_you_mean_html_erb___3816582838178819105_2157568400 at /Users/Vivian_Chu/git/tmp/damsrepo-oct24-14/damsrepo-tomcat/damspas/app/views/catalog/_did_you_mean.html.erb:5)
DEPRECATION WARNING: Calling URL helpers with string keys controller is deprecated. Use symbols instead. (called from block in _app_views_catalog__did_you_mean_html_erb___3816582838178819105_2157568400 at /Users/Vivian_Chu/git/tmp/damsrepo-oct24-14/damsrepo-tomcat/damspas/app/views/catalog/_did_you_mean.html.erb:5)
DEPRECATION WARNING: Calling URL helpers with string keys controller is deprecated. Use symbols instead. (called from block in _app_views_catalog__did_you_mean_html_erb___3816582838178819105_2157568400 at /Users/Vivian_Chu/git/tmp/damsrepo-oct24-14/damsrepo-tomcat/damspas/app/views/catalog/_did_you_mean.html.erb:5)
DEPRECATION WARNING: Calling URL helpers with string keys controller is deprecated. Use symbols instead. (called from block in _app_views_catalog__did_you_mean_html_erb___3816582838178819105_2157568400 at /Users/Vivian_Chu/git/tmp/damsrepo-oct24-14/damsrepo-tomcat/damspas/app/views/catalog/_did_you_mean.html.erb:5)
.

Finished in 18.9 seconds
1 example, 0 failures

**Comment by escowles** [comment]
No, this is the output I get:

[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/uber-0.0.11/lib/uber/inheritable_attr.rb:25: warning: circular argument reference - uncloneable
Run options: include {:locations=>{"./spec/features/dams_unit_spec.rb"=>[45]}}
.

Finished in 6.56 seconds
1 example, 0 failures
[Coveralls] Outside the Travis environment, not sending data.

**Comment by VivianChu** [comment]
Thanks Esme.  It might related to my local environment problem.

**Pull request closed without merging**
