### PR TITLE
Enable the newrelic gem.

### PR DESCRIPTION
**Pull request by lsitu**
Clean up the gemfile lock.

### CODE REVIEW

**Comment by mcritchlow** [comment]
we need for the NewRelic gem to be included in production for this release, and it is currently commented out in the Gemfile. It looks like Ron did that directly.

@lsitu - Can you please uncomment so we can get it built and tested out on staging and eventually prod?

**Comment by lsitu** [comment]
Yes. I've made it but the PR header doesn't make sense.Does it matter?

**Comment by mcritchlow** [comment]
You should be able to edit the title of the PR in the Github UI

**Comment by lsitu** [comment]
@mcritchlow: Done!

**Comment by mcritchlow** [comment]
:+1:

**Pull request merged**
