### PR TITLE
Fixes #248 - audio streaming issue involving Flash and Chrome

### LINKED ISSUE #248: Investigate streaming issues involving Flash and Chrome
Some background: [DI-121](https://lib-jira.ucsd.edu:8443/browse/DI-121)

Several people on that ticket were unable to stream _any_ DAMS audio objects using Chrome. Specific error is "Flash plugin failed to load". 
Firefox seems to be fine. 
(see image below from Cristela)

My machine manages to stream audio fine in Chrome. My specs are:
Chrome 54.0.2840.71 m (64-bit)
Flash Plugin Version (via chrome://plugins/): 23.0.0.205 (PPAPI)

browserissue-screenshot-1

### PR DESCRIPTION
**Pull request by VivianChu**
Fix audio streaming issue

Update the player height

Update the video player height

Update deploy config for qa

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - please review, comment, etc....  Thanks

**Comment by mcritchlow** [comment]
@VivianChu - so if I'm reading the config right, does this mean that Flash is no longer support in the via the player?

**Comment by VivianChu** [comment]
@mcritchlow No, it still support via the player.  Firefox still uses flash to play the audio.

**Comment by VivianChu** [comment]
@mcritchlow I ran the rebuild process for CircleCi #385 and the tests passed.  https://circleci.com/gh/ucsdlib/damspas/385?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
However, the circleci checks for this PR is still reference the failed tests #383.

**Comment by dt-ucsd** [comment]
@VivianChu I am curious about the height change. What does that do?

**Comment by VivianChu** [comment]
@dt-ucsd - if the height is greater than 50, it works for Chrome.  It's similar like the Star report that use the same jwplayer. If less than that, it will display flash plugin error.

**Comment by VivianChu** [comment]
@lsitu The bracket is not missing if you look at the file again.  It's just on the same line.  The bracket I just added make it extra which is wrong.  I will remove the extra bracket and move the other bracket to the second line  to make it easier to see.

**Comment by lsitu** [comment]
@VivianChu Yes, sorry now I see it.

**Comment by VivianChu** [comment]
@lsitu I will squash the commits when CircleCI is done running.

**Comment by VivianChu** [comment]
@ucsdlib/developers - The commits have been squashed.  Would you please review again?  Thanks

**Comment by dt-ucsd** [comment]
@VivianChu that's strange, but good to know. i wouldn't have expected height to be a factor. thanks for the info!

**Comment by mcritchlow** [comment]
@VivianChu in light of https://github.com/ucsdlib/dmr/issues/104 should we hold off on merging this? Or would you prefer that this commit goes in and is released prior to the upgrade?

**Comment by VivianChu** [comment]
@mcritchlow It depends on how soon we want to upgrade the jwplayer.  I'm still waiting for Gabriela and Kirk to test more for DMR.  I think I prefer that this commit goes in and is released prior to the upgrade.

**Comment by mcritchlow** [comment]
@VivianChu ok, sounds good. 

@ucsdlib/developers - can you all please review?

**Comment by hweng** [comment]
:+1:

**Comment by VivianChu** [comment]
@ucsdlib/developers Thanks everyone for reviewing.  Could anybody please merge this PR?  Thanks

**Pull request merged**
