### PR TITLE
Update title to display subscripts and superscripts

### LINKED ISSUE #348: ensure subscripts and superscripts display in collection and object page title
"sub" and "sup" tags display in DAMS properly in the following places:
object page description (https://librarytest.ucsd.edu/dc/object/bd9812384c)
collection page description (https://librarytest.ucsd.edu/dc/collection/bd68430724)
title in search results (https://librarytest.ucsd.edu/dc/search?f%5Bcollection_sim%5D%5B%5D=Center+for+Aerosol+Impacts+on+Chemistry+of+the+Environment&id=bd5034217p)

They do not display properly in titles on collection or object pages (https://librarytest.ucsd.edu/dc/object/bd91298321)
I confirmed this impacts CLRs too by updating a collection page title to include a subscript.

Super/Subscripts do display in the data view https://librarytest.ucsd.edu/dc/collection/bd91298321/data

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #348  ; refs #348 

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
Would it be possible to add a test that demonstrates this change?

**Comment by VivianChu** [comment]
@mcritchlow - A test has been added to demonstrate this change.

**Comment by mcritchlow** [comment]
LGTM :+1: 
- @hweng or @lsitu could you please review (and merge is looks good to you)

**Comment by hweng** [comment]
:+1:

**Pull request merged**
