### PR TITLE
Update staging deploy config. DHH-833

### PR DESCRIPTION
**Pull request by VivianChu**
Update the staging deploy config. DHH-833

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - Please review, comment, etc... Thanks.

**Comment by mcritchlow** [comment]
👍

**Comment by lsitu** [comment]
:+1:

**Comment by hweng** [comment]
👍

**Comment by VivianChu** [comment]
Thanks everyone for reviewing and Huawei for merging.

**Pull request merged**
