### PR TITLE
Fixes #251- Implement the delete function and migrate to SHARE versio…

### LINKED ISSUE #251: Feature: Initiate delete from SHARE
Please add the ability to initiate a deletion request via the SHARE Notify service for a give record.

This can be in the form of a new link that is only accessible to the group that is able to create SHARE records for Collections. 

> For the items to delete, we double-checked in the Hydra gem that there is a method to delete items from SHARE. So, the easiest thing is for you to initiate the delete requests from your end for the records you would like deleted. There is an example of doing a delete request in the README for the gem: 
> 
> - https://github.com/projecthydra-labs/share_notify/blob/master/README.md
> 
> The example references calling the delete method in push_document.rb: https://github.com/projecthydra-labs/share_notify/blob/master/lib/share_notify/push_document.rb It essentially sets a value of “status:deleted” in the otherProperties before pushing the record to SHARE. At a minimum, you will want to have the canonical uri set for any records you want to delete, but you could also send the original metadata that was sent over with the additional property set. 

Testing/QA Group: @gamontoya @hjsyoo

### PR DESCRIPTION
**Pull request by hweng**
…n 2 API.

Fixes #251 ; refs #251

Changes proposed in this pull request:
*  Migrated to SHARE version 2 API.
*  Implemented delete a record from SHARE function.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by VivianChu** [comment]
👍

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
@ucsdlib/developers Can anyone merge this PR please? Another ticket https://github.com/ucsdlib/damspas/issues/270 is depending on it. Thanks!

**Comment by hweng** [comment]
Thank you @ucsdlib/developers for reviewing and @mcritchlow for merged it.

**Pull request merged**
