### PR TITLE
Add user group dams-editor and remove the dams-rci group. DM-186

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DM-186

### CODE REVIEW

**Comment by mcritchlow** [comment]
@ucsdlib/developers please take a look. this is a significant change everyone should at least be aware of

**Comment by lsitu** [comment]
@mcritchlow Will circleci download the latest damsrepo code for test or not? I am seeing some tests for access control failed.

**Comment by VivianChu** [comment]
@lsitu you have to deploy damsrepo to pontos. Circleci doesn't download damsrepo.

**Comment by lsitu** [comment]
@VivianChu Thanks. I think the configuration for damsrepo is outed. I am rebuilding damspas now and it looks good.

**Comment by mcritchlow** [comment]
@ucsdlib/developers we still need review on this PR. Thanks.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Comment by lsitu** [comment]
@ucsdlib/developers Could anyone merge it? Thanks.

**Comment by lsitu** [comment]
Thank you all for viewing and merging the PR.

**Pull request merged**
