### PR TITLE
Feature/music icon

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - Please review, comment, etc. at your earliest convenient.  Thanks

**Comment by mcritchlow** [comment]
👍

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
👍

**Comment by VivianChu** [comment]
Thanks @ucsdlib/developers for reviewing.  Could anybody please merge this PR?  Thanks

**Pull request merged**
