### PR TITLE
Use alpine for damspas

### LINKED ISSUE #501: Try switching from PhantomJS to Headless Chrome(ium)
### Descriptive summary

Try:
- Bump `capybara` to a current version. ours is insanely old.
- Add `rspec-retry` gem and tweak `config.default_retry_count = 2` since loading might be a tad slower (only if needed)
- Change from `poltergeist` driver to `selenium-chrome-headless` (mostly seems to be in `features/dams_object_spec`
- Update `Dockerfile` to use/install chromium and chromedriver and use Alpine linux
- Update `.circleci/config` to use/install chromium and chromedriver

### Rationale

PhantomJS is no longer maintained, and the predominant usage is now headless chrome with capybara using chromedriver. This would also potentially allow us to more easily use Alpine linux for the Docker/Docker Compose related builds, since chromium and chromedriver are packaged (same with ubuntu/debian)

### PR DESCRIPTION
**Pull request by mcritchlow**
Fixes #501 

#### Local Checklist
- [x] Tests written and passing locally?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [x] Configuration updated (if needed)?
- [x] Documentation updated (if needed)?

#### What does this PR do?
Note this doesn't actually 'fix' #501, but after some research yesterday I've come to realize that while I can setup chromium and chromedriver to replace phantomjs in our Docker setup, far too many tests would need to be rewritten because we'd need to bump Capybara to a modern version. I made some effort to see how much work this would be, and it's more than seems to be of any value to us all, in my opinion.

So instead I've focused on replacing the Debian-based image for local development with an Alpine based one. This cuts the overall image size for damspas from 2.2G to 650M. Which is significant.. I might be able to get it even smaller with a multi-stage build, but I think this is good for now.

The two other commits are housecleaning and preparation to make the Alpine shift possible.

##### Why are we doing this? Any context of related work?
We are doing this to try and cut down on the footprint of using Docker for our local dev environment. This brings all of our images to using Alpine linux, which is the smallest starting point we can go with for now.

#### Where should a reviewer start?
- See `docker/README.md` changes, feedback welcome
- Please run the `docker/dev/docker-compose.yml` setup locally if you can, since we can't use it in circleci.
- Note that the ruby version test was changed to `skip` since it actually passes in the dev/non-circleci context and would then trigger an error. 

#### Manual testing steps?
- Please run the `docker/dev/docker-compose.yml` setup locally if you can, since we can't use it in circleci.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
@ucsdlib/developers - anyone have a chance to try this out? Curious if there's feedback or issues that need addressing. thanks

**Comment by hweng** [comment]
@mcritchlow I'm going to try and let you know.

**Comment by lsitu** [comment]
@mcritchlow I tried to rebuild it with `docker-compose -f docker/dev/docker-compose.yml up`. But I see lots of logging message for solr_1 container and finally it got hanged:
...
solr_1      | 175462492 INFO  (commitScheduler-9-thread-1) [   x:blacklight] o.a.s.c.SolrDeletionPolicy SolrDeletionPolicy.onCommit: commits: num=2
solr_1      | 	commit{dir=/opt/solr/server/solr/mycores/blacklight/data/index,segFN=segments_ftx,generation=20517}
solr_1      | 	commit{dir=/opt/solr/server/solr/mycores/blacklight/data/index,segFN=segments_fty,generation=20518}
solr_1      | 175462493 INFO  (commitScheduler-9-thread-1) [   x:blacklight] o.a.s.c.SolrDeletionPolicy newest commit generation = 20518
solr_1      | 175462493 INFO  (commitScheduler-9-thread-1) [   x:blacklight] o.a.s.s.SolrIndexSearcher Opening Searcher@2faf96b0[blacklight] main
solr_1      | 175462494 INFO  (searcherExecutor-7-thread-1-processing-x:blacklight) [   x:blacklight] o.a.s.c.QuerySenderListener QuerySenderListener sending requests to Searcher@2faf96b0[blacklight] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
solr_1      | 175462494 INFO  (searcherExecutor-7-thread-1-processing-x:blacklight) [   x:blacklight] o.a.s.c.QuerySenderListener QuerySenderListener done.
solr_1      | 175462494 INFO  (searcherExecutor-7-thread-1-processing-x:blacklight) [   x:blacklight] o.a.s.c.SolrCore [blacklight] Registered new searcher Searcher@2faf96b0[blacklight] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
solr_1      | 175462495 INFO  (commitScheduler-9-thread-1) [   x:blacklight] o.a.s.u.DirectUpdateHandler2 end_commit_flush

**Comment by hweng** [comment]
@mcritchlow 
I tried  `docker-compose -f docker/dev/docker-compose.yml up`,  It works fine that I got:
`tomcat_1    | INFO: Server startup in 7281 ms
`
Then tried:
`docker-compose -f docker/dev/docker-compose.yml exec web bundle exec rake spec`
I got:
`ERROR: No container found for web_1`

Tried:
`docker-compose -f docker/dev/docker-compose.yml exec -e RAILS_ENV=test web bundle exec rake db:create`
I got:
`ERROR: No container found for web_1`

**Comment by VivianChu** [comment]
@hweng - I got that error earlier too, but then I tried this to build the container - docker-compose -f docker/dev/docker-compose.yml build

**Comment by lsitu** [comment]
@mcritchlow I run it again with `docker-compose -f docker/dev/docker-compose.yml up` and now I see it stalled at tomcat_1:
...
tomcat_1    | INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
tomcat_1    | Aug 02, 2018 10:34:04 PM org.apache.catalina.startup.HostConfig deployDirectory
tomcat_1    | INFO: Deployment of web application directory /usr/local/tomcat/webapps/docs has finished in 91 ms
tomcat_1    | Aug 02, 2018 10:34:04 PM org.apache.coyote.AbstractProtocol start
tomcat_1    | INFO: Starting ProtocolHandler ["http-apr-8080"]
tomcat_1    | Aug 02, 2018 10:34:05 PM org.apache.coyote.AbstractProtocol start
tomcat_1    | INFO: Starting ProtocolHandler ["ajp-apr-8009"]

**Comment by mcritchlow** [comment]
@VivianChu - Regarding your error. Did you run the db:create db:migrate command before running the test suite? That would definitely cause essentially everything to fail

@lsitu - That's interesting. I might try killing/removing the tomcat container and starting clean. One thing I've noticed that's somewhat related is you need to keep an eye on the RAM usage when you fire these things up. I think once I didn't have enough free RAM and the Solr container stalled out. 

@hweng - :+1: to @VivianChu's recommendation, that's actually in the updated `docker/README` file in this PR. Hopefully that helps get you past that part.

Thanks all

**Comment by VivianChu** [comment]
@mcritchlow - I did run db:create db:migrate yesterday.  Today I tried db:create db:migrate again and I got Gem.gunzip called from /usr/local/bundle/gems/unicode-display_width-1.2.1/lib/unicode/display_width/index.rb:5.
damspas_test already exists
I tried docker-compose -f docker/dev/docker-compose.yml exec web bundle exec rake spec  and a lot of tests failed.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Pull request merged**
