### PR TITLE
Added the newrelic gem for performance tracking. DHH-806

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DHH-806

### CODE REVIEW

**Comment by mcritchlow** [comment]
gem inclusion looks great. 

it would be nice to get the config file sorted out as part of this.

here's a sample from one of Stanford's apps: https://github.com/sul-dlss/SearchWorks/blob/master/config/newrelic.yml

@rstanonik do you have the config from NewRelic? in our current deployment config for damspas, that will probably need to go in private config.

**Comment by lsitu** [comment]
@mcritchlow I've added the content for the sample yml newrelic.yml.sample. rstanonik may want to add the real file to share/config folder for privacy and create a symlink for it. If we go this way, do we still need to add the real newrelic.yml to private_config?

**Comment by mcritchlow** [comment]
@lsitu i'd prefer that we treat this in the same way we treat all private configuration for this app. That will make migration to the new model Vivian is working on much easier. So, let's please go that route. Once you have it setup in private config please let me know, and I'll merge this. 

Also, I'm not sure whether you want Ron's commit on the PR or not.

**Comment by lsitu** [comment]
@mcritchlow I've added the yml file to private_config: https://lib-stash.ucsd.edu/projects/ND/repos/private_config/commits/c4643ab7562f8438ab1b9ca8b03c90e0d1f6d5cd

**Comment by mcritchlow** [comment]
:+1:

**Pull request merged**
