### PR TITLE
Distinguished object ARKs/URLs for curator and non-curator access for RDCP statistics reporting. DM-183

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DM-183

### CODE REVIEW

**Comment by mcritchlow** [comment]
@lsitu looks like the test suite had some failures. Please ping the group for review once it's passing.

**Comment by lsitu** [comment]
@mcritchlow Sure. I ran it a couple of times locally again and all passed. It looks like all errors are related to access controls. Do you know what might be an issue?

**Comment by lsitu** [comment]
@mcritchlow I updated the test context description text to force ci/circleci to ran the test again, and the test suite passed now.

**Comment by lsitu** [comment]
@ucsdlib/developers - Please review, comment, etc... Thanks

**Comment by lsitu** [comment]
@ucsdlib/developers - Please review. Thanks

**Comment by VivianChu** [comment]
@lsitu 👍   Could you please also squash your commits?  It would be easier to see your changes in 2 files instead of seeing my changes for the previous PR https://github.com/ucsdlib/damspas/pull/227/commits/0547ff99144f32faa13d2bd39184bcdbf92dda11  Thanks

**Comment by lsitu** [comment]
@VivianChu Yep, I just did a rebase and your changes are gone now. Thanks.

**Comment by hweng** [comment]
:+1:

**Comment by lsitu** [comment]
@VivianChu @hweng Could you merge it when you get a chance? Thanks.

**Comment by lsitu** [comment]
@ucsdlib/developers Thanks everyone for the review, and Vivian for the merging.

**Pull request merged**
