### PR TITLE
Feature/update doi

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes https://github.com/ucsdlib/damsrepo/issues/73

#### Local Checklist
- [x] Tests written and passing locally?
- [x] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [ ] Documentation updated (if needed)?

#### What does this PR do?

Add update doi record function

#### Screenshots
- Before DOI Update

beforedoiupdate2

-After DOI Update

afterdoiupdate2

-If there's doi, this message will be displayed.

successfulmsg

-If no DOI is minted, this error message will be displayed.

errordoiupdatemsg

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by mcritchlow** [comment]
quick question, the comment in the last screenshot is `-If no DOI is minted, this error message will be displayed.` I'm not clear on the language here i guess. if we're updating a DOI, then there is already a DOI identifier, right? So I'm wondering how you triggered the error you're demonstrating with an invalid identifier.

**Comment by VivianChu** [comment]
@mcritchlow - The link for Mint DOI and Update DOI record is displayed for all records.  However, if you click on Update DOI record link before clicking the Mint DOI link, then that error will be displayed.  Or do think if I should hide the Update DOI record link unless that record has a DOI identifier?

**Comment by mcritchlow** [comment]
@VivianChu Ah, I see. That makes sense.

I think if it's not too much trouble to hide the Update DOI link unless there is already a DOI associated with the record, that would be nice and avoid someone accidentally doing that.

I suppose likewise you could hide the Mint DOI link if the object already has a DOI?

**Comment by VivianChu** [comment]
@mcritchlow - Sounds good.  I'll make an update to hide the Mint DOI and Update DOI link.  I'll keep you posted.

**Comment by VivianChu** [comment]
@mcritchlow - The function has been updated to hide/show doi link.  It has been deployed to staging. Here are the screen shots.
//DOI minted record. The Update DOI record link is displayed and the Mint DOI link is hidden.
updatedoi

//No DOI minted record.  The Update DOI record link is hidden and the Mint DOI link is displayed.
nodoiid

**Comment by lsitu** [comment]
👍

**Pull request merged**
