### PR TITLE
Gemnasium - Update Dependencies. DHH-845

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - Please review, comment, etc... Thanks

**Comment by mcritchlow** [comment]
@VivianChu looks great overall 👍 

why the need for the new rspec-mocks gem?

**Comment by VivianChu** [comment]
@mcritchlow It's related to rspec-rails 3.5.0 update.  It doesn't let me update because the rspec-mocks gem is locked at the older version.

**Comment by mcritchlow** [comment]
Ah, gotcha. Thanks for clarifying!

**Comment by hweng** [comment]
:+1:

**Comment by VivianChu** [comment]
Thanks everyone for reviewing.  Could anybody please merge this PR?

**Comment by hweng** [comment]
@ucsdlib/developers,  I merged it and the commit showed up in the develop branch.

**Comment by VivianChu** [comment]
Thanks @hweng for merging

**Pull request merged**
