### PR TITLE
vrr: use rails logger for rest-client

### PR DESCRIPTION
**Pull request by mcritchlow**
It appears there are issues, yet to be determined, with batch processing vrr expirations.

This patch attaches the [rest-client gem](https://github.com/rest-client/rest-client#logging) to the Rails logger defined for the application. 

This will result in logging when API requests are made, hopefully giving us more insight into what may be going wrong.

Example output:

```
RestClient.get "no_aeon_api_provided/Requests", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate", "X-AEON-API-KEY"=>"no_aeon_key_provided", "content-type"=>"text/json"
# => 200 OK |  0 bytes
=> ""
```

#### Local Checklist
- [ ] Tests written and passing locally?
- [ ] Code style checked?
- [x] QA-ed locally?
- [x] Rebased with `master` branch?
- [ ] Configuration updated (if needed)?
- [ ] Documentation updated (if needed)?

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by hweng** [comment]
Does all the http requests be automatically added to logging output? Or you need to call the method somewhere in the code to get output?

**Comment by mcritchlow** [comment]
@hweng - great question. they get automatically logged. An alternative is to pass in a logger when a rest client is created: `resource = RestClient::Resource.new 'http://example.com/resource', log: Logger.new(STDOUT)`

But this initializer seemed like a nice way of:
- leaving the existing code alone
- ensuring that any additional rest-client usage/instances doesn't accidentally forget to add logging

see: https://github.com/rest-client/rest-client#logging

**Comment by hweng** [comment]
@mcritchlow It sounds promising. Will see how the logger output looks like and how it is helpful. thank you for the explanation.

**Comment by mcritchlow** [comment]
@hweng - yeah, i think it's at least going to hopefully be a helpful starting point. To your earlier point, we may also need to do more specific logging around the vrr issues, but this at least gets us whatever logging we can get from the rest client gem directly. Thanks!

**Pull request merged**
