### PR TITLE
Improve log output with STDOUT logger and lograge with logstash format. DHH-844

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DHH-844

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Please review and comment. Thanks.

**Comment by mcritchlow** [comment]
Do we have `LOG_LEVEL` defined anywhere in the config files? If not, should we? The fallbacks from the `fetch` call (`:info` for production, for example) look reasonable to me.

**Comment by lsitu** [comment]
Yes, I don't think we've defined LOG_LEVEL in the config files but I assume the default value will taking effects. Would you like to add it to environment variables or just remove it and set it to the default value?

**Comment by mcritchlow** [comment]
I think we should probably do one or the other. Either put it in the ENV, since the code in the PR is referencing it, or just update the code in the PR to use a static value. I'm open to whichever option makes sense, but as it the fetch call to ENV isn't really doing anything.

**Comment by lsitu** [comment]
@mcritchlow I've move ahead to remove the lines for configuration with the environment variable LOG_LEVEL. So the default info log level should be applied for all environments now.

**Comment by mcritchlow** [comment]
@VivianChu @hweng - any thoughts or comments?

**Comment by VivianChu** [comment]
👍

**Comment by VivianChu** [comment]
@lsitu I'm wondering how come we don't use debug log level for other environments except production.

**Comment by lsitu** [comment]
@VivianChu Yes, I think by default only prod is info, while the default for other environment should be in debug mode, and this is what our system currently do. We can turn on it with environment variable setting later if it's not the case. Sorry about the confusing message.

**Comment by VivianChu** [comment]
Thanks @lsitu for clarification.

**Comment by hweng** [comment]
:+1:

**Comment by lsitu** [comment]
Thank you all for reviewing and merging the PR.

**Pull request merged**
