### PR TITLE
Removed collection push trigger from damsolrizer. (DHH-843)

### PR DESCRIPTION
**Pull request by hweng**

### CODE REVIEW

**Comment by hweng** [comment]
@ucsdlib/developers - please review, comment, etc... Thanks

**Comment by mcritchlow** [comment]
👍

**Comment by lsitu** [comment]
👍

**Comment by lsitu** [comment]
It looks like the thumb :+1 👍  is not showing up.

**Comment by VivianChu** [comment]
:+1:

**Comment by hweng** [comment]
Thanks everyone for reviewing and @VivianChu for merging

**Pull request merged**
