### PR TITLE
Feature/collections search

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - Please review, comment, etc. at your earliest convenient.  Thanks

**Comment by mcritchlow** [comment]
two questions:
* Does this PR satisfy the second user story of the JIRA ticket ("Search this collection...")
* What will display, assuming this PR is merged, when a user does not come in via the unit links? For example, if I am at the /dc homepage and just hit the search button. Will I continue to get the current text?

**Comment by VivianChu** [comment]
@mcritchlow I miss the second user story.  I will add that to the code.

**Comment by VivianChu** [comment]
@mcritchlow   For the second user story , I'm waiting for Ho Jung to respond to my question. https://lib-jira.ucsd.edu:8443/browse/DHH-824?focusedCommentId=46848&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46848
For your number question, if you hit the search button, you still get the old text "Search Digital Collections"  http://library.ucsd.edu/dc/search?utf8=%E2%9C%93&q=
The unit scope and other search query parameters don't preserve when you go to /dc home page. I think it would be better to use the generic text like the home page search box "Search..." I will ask Ho Yung if we can use it instead. Thanks

**Comment by VivianChu** [comment]
@mcritchlow  I updated the code to support the second user story.  For your other question, Ho Jung thought the text is fine the way it is.

**Comment by mcritchlow** [comment]
👍 but want to make sure at least @lsitu can take a look. @hweng is out today

**Comment by lsitu** [comment]
👍

**Pull request merged**
