### PR TITLE
Update http links to https

### LINKED ISSUE #304: completely https-ify damspas
### Descriptive summary

There are several instances where we're still referring to http for damspas. We need to fix these and move to https. A few that I found. If there are others, please add here:

Sitemap: https://github.com/ucsdlib/damspas/blob/3bb7eb57c071b713f7c7ad27d37a1a30bc073c96/config/sitemap.rb#L2

Wowza: https://github.com/ucsdlib/damspas/blob/develop/config/environments/production.rb#L73

Zoomify: https://github.com/ucsdlib/damspas/blob/develop/config/environments/production.rb#L82

Rails.host_name: https://github.com/ucsdlib/damspas/blob/develop/config/environments/production.rb#L84

https://github.com/ucsdlib/damspas/blob/develop/config/environments/staging.rb#L63

https://github.com/ucsdlib/damspas/blob/develop/config/environments/staging.rb#L65

https://github.com/ucsdlib/damspas/blob/3bb7eb57c071b713f7c7ad27d37a1a30bc073c96/app/assets/javascripts/home-page.js#L4

https://github.com/ucsdlib/damspas/blob/develop/app/assets/stylesheets/custom-object-viewer.css.scss#L108

https://github.com/ucsdlib/damspas/blob/develop/app/helpers/catalog_helper.rb#L138

https://github.com/ucsdlib/damspas/blob/develop/app/views/layouts/_footer.html.erb#L15

https://github.com/ucsdlib/damspas/blob/develop/app/views/layouts/_header.html.erb#L59

### Rationale

Having folks use http links may cause mixed protocol errors. Browsers are increasingly strict against this, and we _may_ be causing downstream issues for our users by having these http remnants.

### PR DESCRIPTION
**Pull request by VivianChu**
Fixes #304 ; refs #304 

Update http links to https link to fix mixed protocol errors.

@ucsdlib/developers - please review

### CODE REVIEW

**Comment by gamontoya** [comment]
@mcritchlow @ucsdlib/domm Yes, I'll be happy to help, but we need to know exactly what we're testing for.

**Comment by mcritchlow** [comment]
@gamontoya will do 👍  we'll make a list on the release ticket

@VivianChu - only thing I noticed after the fact. What about changing the instances of `libraries` to `library` in the URLs? I think those are mostly in the css/js files.

**Comment by VivianChu** [comment]
@mcritchlow - All instances of libraries have been changed to library.

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
👍

**Pull request merged**
