### PR TITLE
Fix the access control bug adjust the editor tools UI display for curators and editors. DM-186

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DM-186
https://lib-jira.ucsd.edu:8443/browse/DEPLOYKEY-269

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers This is a hot fix for the deployment. Please review and comments. Thanks.

**Comment by mcritchlow** [comment]
👍

**Comment by VivianChu** [comment]
👍

**Comment by mcritchlow** [comment]
@lsitu - one question, this is described as a hotfix, yet the PR is setup to be merged into the `develop` branch. Is that your intention here? Just want to make sure we get this in the right branch(es).

**Comment by lsitu** [comment]
@mcritchlow Yes, this is a good question. I think we can merge it to the develop branch and then merge it to the release branch since I don't see other commits in the develop branch yet. I just think about whether it'll be better for others changes or not. But I can change it the release branch if you think it works better.

**Comment by VivianChu** [comment]
@lsitu the release branch 1.58 has been deleted.  Does that mean we need another release branch 1.59?

**Comment by hweng** [comment]
:+1:

**Comment by mcritchlow** [comment]
if the release branch is deleted, and we need to get this out to production, then we should probably do a true hotfix (https://github.com/nvie/gitflow#creating-featurereleasehotfixsupport-branches) where the commit gets merged into master and develop, and then we ask OPS to deploy to production. Is that the situation here, or could this change simply go into the next release?

**Comment by lsitu** [comment]
@mcritchlow, @VivianChu: I don't know what could work better in this case. But merging it to develop branch and then the master branch for a true hotfix sounds good to me if we really want a hotfix. Maybe we can ask Gabriela to see whether she can wait for the next release instead of a hotfix?

**Comment by mcritchlow** [comment]
@lsitu sounds good, if you can ask Gabriela about urgency then we can take it from there.

**Pull request merged**
