### PR TITLE
Include facet anatomy in Refine Your Search and exclude series, cultural context from the topic facet. DHH-793

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DHH-793

### CODE REVIEW

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comment... Thanks.

**Comment by mcritchlow** [comment]
👍

**Comment by VivianChu** [comment]
👍

**Comment by lsitu** [comment]
@hweng Could you review and merge it if it looks good to you so that @VivianChu can move ahead to create the new release for damspas? Thanks.

**Comment by hweng** [comment]
:+1:

**Comment by lsitu** [comment]
@ucsdlib/developers Thank you all!

**Comment by hweng** [comment]
@ucsdlib/developers pull request has been merged and the commits show in develop branch.

**Pull request merged**
