### PR TITLE
Fixes #271 - https streaming issue on latest chrome

### LINKED ISSUE #271: https streaming issue on latest chrome
From Ron:
```
While Dan was trying to add a video to LISN, he discovered that streaming no longer worked for the latest chrome.
 
The problem seems to be that https LISN includes http streaming links and chrome no longer allowes http links on https pages.
 
I added an https streaming port to the streaming server and changed the LISN streaming-video macro to use it.
 
The change was from http://lib-streaming.ucsd.edu:1935 to https://lib-streaming.ucsd.edu:1936.
 
And I added a manifest.mpd source and made the source order manifest.mpd, playlist.m3u8, rmtps (from rmtp) last.
 
We confirmed that https streaming works for chrome, firefox, IE, and Edge.
 
Dev, you will need to make similar changes for DAMS and DMR.
 
Additionally, make manifest.mpd first in the source list.
 
Ron
```

### PR DESCRIPTION
**Pull request by VivianChu**
Update deploy config

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - Please review, comment, etc... 
It has been deployed to qa and tested on Chrome and other browsers.

//complex video
http://libraryqa.ucsd.edu/dc/object/bb3482439v

//single video
http://libraryqa.ucsd.edu/dc/object/bb1571482k

//audio
http://libraryqa.ucsd.edu/dc/object/bb23565552

//audio complex
http://libraryqa.ucsd.edu/dc/object/bb2629146f

Thanks

**Comment by mcritchlow** [comment]
Generally 👍 here. I'm all for https'ing everything we can. Would be nice to test this out on staging and have folks confirm. Any concerns with the changes @lsitu or @hweng ?

**Comment by lsitu** [comment]
👍

**Comment by VivianChu** [comment]
@mcritchlow I can deploy it to staging after the merge.  Thanks

**Pull request merged**
