### PR TITLE
Update jwplayer config to play video using html5. DHH-832

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - Please review, comment, etc. at your earliest convenient.  Thanks

**Comment by mcritchlow** [comment]
overall, 👍 
have we confirmed this is working as expected for DMR?

**Comment by VivianChu** [comment]
@mcritchlow  Kirk and I confirmed this is working as expected for DMR

**Comment by mcritchlow** [comment]
@VivianChu 👏

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
@VivianChu 👍 if this is not expect to have tests to reflect change.

**Comment by VivianChu** [comment]
Thanks everyone for reviewing and @hweng for merging

**Pull request merged**
