### PR TITLE
Feature/home page update

### PR DESCRIPTION
**Pull request by dt-ucsd**
Updated home page as requested. Modified design of lower half of the
page to better suit current content. Updated <title> text. Updated HTTP
links to HTTPS.

### CODE REVIEW

**Comment by mcritchlow** [comment]
👍 assuming CircleCI is happy.

**Comment by mcritchlow** [comment]
@jhriv @lsitu @VivianChu - looks like running the test suite on pontos may be struggling again. Could someone please take a look?

**Comment by VivianChu** [comment]
@mcritchlow - I'm running the build process again to see if it helps.

**Comment by mcritchlow** [comment]
@VivianChu - Thanks for cleaning that up! The PR look ok to you? If so, please merge for @dt-ucsd

**Pull request merged**
