### PR TITLE
Default display of first component file. DHH-839

### PR DESCRIPTION
**Pull request by VivianChu**

### CODE REVIEW

**Comment by VivianChu** [comment]
@ucsdlib/developers - please review, comment, etc...  Thanks

**Comment by VivianChu** [comment]
@ucsdlib/developers - please review, comment, etc... Thanks

**Comment by lsitu** [comment]
👍

**Comment by hweng** [comment]
:+!:

**Comment by hweng** [comment]
:+1:

**Comment by VivianChu** [comment]
Thanks everyone for reviewing and @hweng for merging

**Pull request merged**
